version: '2'
services:
  web:
    build: .
    image: liuggio/bashd
    ports:
     - "8080"
    networks:
      - mynet
    volumes:
       - ./app:/app
    depends_on:
      - "redis"
    labels:
      - "com.workshop.web.description=ssh"
      - "com.workshop.web.version=v1"
    environment:
      - ENV_ENVIRONMENT=development
      - ENV_INCR_NAME=hit
  redis:
    image: redis:alpine
    networks:
      - mynet

networks:
  mynet:
    driver: bridge